apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: career-coach-prod
resources:
  - namespace-prod.yaml
  - secrets-prod.yaml
  - postgres-init-configmap.yaml
  - persistent-volume.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-deployment-prod.yaml
  - redis-service.yaml
  - configmap.yaml
  - frontend-deployment-prod.yaml
  - backend-deployment-prod.yaml
  - ai-service-deployment-prod.yaml
  - ingress-prod.yaml
