apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: career-coach-prod
  labels:
    app: ai-service-prod
    tier: ai
spec:
  type: ClusterIP
  ports:
  - port: 5100
    targetPort: 5100
    protocol: TCP
  selector:
    app: ai-service-prod
