apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: career-coach-prod
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: adminpassword
  REDIS_PASSWORD: redispassword
  JWT_SECRET: super_secret_jwt_token_key_for_production
  GEMINI_API_KEY: AIzaSyDiLz-GvOPpmLVxDH8nMBK99mkvQQyzyQ0
  GEMINI_PROJECT_NAME: projects/583354103787
  GEMINI_PROJECT_NUMBER: 583354103787
  AI_MODEL_API_KEY: AIzaSyDiLz-GvOPpmLVxDH8nMBK99mkvQQyzyQ0
